version: "3.8"
services:
  camformant-client:
    container_name: camformant_client_container
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    env_file: .env 
    environment:
      - DOCKER_ENV=true
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./src:/app/src  
    networks:
      - custom-network   
networks:
   custom-network:
      external: true  # Use an external, shared network 

